// Not sure how this works. Isn't that nice, familiar territory? :) I think what
// actually happens is that when a C++ exception happens, the exception is
// somehow handed over to this function (probably by stack magic) and allows us
// to do our thing.

void translate_yoda_error();
